### ISSUE TITLE
no encoder

### ISSUE THREAD

**Issue by peshi** [Spomky-Labs/lexik-jose-bridge#23] opened 2017-04-27 16:09 UTC
Everything is set-up according to docs - but there's no encoder.

bin/console dump:container|grep encoder
 
```
  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
  You have requested a non-existent service "lexik_jose_bridge.encoder".
```

Using Symfony 3.2.7

**Comment by Spomky** [comment] 2017-04-27 19:25
Hi,

Thank you for reporting me this issue.
I cannot reproduce it. With the command `bin/console debug:container|grep encoder`, I have the following result:

    lexik_jose_bridge.encoder.jwt_creator                                           alias for "jose.jwt_creator.lexik_jose"
    lexik_jose_bridge.encoder.jwt_loader                                            Jose\JWTLoader
    lexik_jwt_authentication.encoder                                                SpomkyLabs\LexikJoseBundle\Encoder\LexikJoseEncoder
    lexik_jwt_authentication.encoder.default                                        Lexik\Bundle\JWTAuthenticationBundle\Encoder\DefaultEncoder
    lexik_jwt_authentication.encoder.lcobucci                                       Lexik\Bundle\JWTAuthenticationBundle\Encoder\DefaultEncoder
    security.encoder_factory                                                        Symfony\Component\Security\Core\Encoder\EncoderFactory
    security.password_encoder                                                       Symfony\Component\Security\Core\Encoder\UserPasswordEncoder

Please note that the service `lexik_jose_bridge.encoder` is not public.

**Comment by chalasr** [comment] 2017-04-27 19:44
Unable to reproduce either.

**Comment by peshi** [comment] 2017-04-27 21:09
I get the same results with a fresh install of Symfony - I'll investigate further why my current project isn't able to receive the encoder properly. - I'll close this for now.

**Comment by peshi** [comment] 2017-04-27 21:37
Ok, I actually used LexikJWTAuthenticationBundle - dev-master.

It doesn't seem too friendly with the new autowiring commit.

```
You have requested a non-existent service "lexik_jose_bridge.encoder".

in ContainerBuilder.php line 803
at ContainerBuilder->getDefinition('lexik_jose_bridge.encoder') in ContainerBuilder.php line 828
at ContainerBuilder->findDefinition('lexik_jwt_authentication.encoder') in LexikJWTAuthenticationExtension.php line 63
at LexikJWTAuthenticationExtension::registerAutowiringTypes(object(ContainerBuilder)) in LexikJWTAuthenticationExtension.php line 56
```

Reverting to 2.3.0 works.

So I guess this could be interesting for both of you :)

**Comment by chalasr** [comment] 2017-04-28 07:45
I'm looking into, thanks for investigating @peshi.

**Comment by chalasr** [comment] 2017-04-28 09:09
Fixed in https://github.com/lexik/LexikJWTAuthenticationBundle/commit/81f73153281d5845b65fbe4fa1e772729916ef4e
@peshi would you mind to retry with your original dependency set?

**Closed** 2017-04-28 09:08 UTC

**Comment by peshi** [comment] 2017-04-28 09:20
@chalasr Tested. It works as expected - thanks for the quick fix and response time! 👍

**Comment by Spomky** [comment] 2017-05-02 08:30
Thanks @chalasr for the quick reply and responsiveness ☺️
